name: Docs

run-name: ${{ github.actor }} is generating docs

on: [pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update pandoc
        run:
          sudo apt-get install pandoc

      - name: Update pip
        run:
          python -m pip install --upgrade pip
      
      - name: Install poetry 
        run:
          pip install poetry==1.1.13
      
      - name: Install package
        run:
          poetry install

      - name: Sphinx build
        run: |
          poetry run sphinx-build -b html docs/ docs/_build/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/_build/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

permissions:
  id-token: write
  contents: read
  pages: write
